### ISSUE TITLE
NotionClient#appendBlockChildren fails (seems to be Jersey + Http PATCH method bug)

### ISSUE THREAD

**Issue by dmitry-weirdo** [seratch/notion-sdk-jvm#44]
`client.appendBlockChildren(pageId, blocksToAppend);` fails with the following exception:

```
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field private final sun.net.www.protocol.https.DelegateHttpsURLConnection sun.net.www.protocol.https.HttpsURLConnectionImpl.delegate accessible: module java.base does not "opens sun.net.www.protocol.https" to unnamed module @5cdd8682
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at notion.api.v1.http.HttpUrlConnPatchMethodWorkaround.setPatchRequestMethod$lambda-0(HttpUrlConnPatchMethodWorkaround.kt:45)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at notion.api.v1.http.HttpUrlConnPatchMethodWorkaround.setPatchRequestMethod(HttpUrlConnPatchMethodWorkaround.kt:36)
	at notion.api.v1.http.HttpUrlConnNotionHttpClient.patchTextBody(HttpUrlConnNotionHttpClient.kt:86)
	at notion.api.v1.http.NotionHttpClient$DefaultImpls.patchTextBody$default(NotionHttpClient.kt:24)
	at notion.api.v1.endpoint.BlocksSupport$DefaultImpls.appendBlockChildren(BlocksSupport.kt:129)
	at notion.api.v1.NotionClient.appendBlockChildren(NotionClient.kt:12)
	at notion.api.v1.endpoint.BlocksSupport$DefaultImpls.appendBlockChildren(BlocksSupport.kt:124)
	at notion.api.v1.NotionClient.appendBlockChildren(NotionClient.kt:12)
	at com.dv.telegram.notion.NotionWrapper.main(NotionWrapper.java:51)
```

The root bug seems to be here — https://github.com/eclipse-ee4j/jersey/issues/4825

**Comment by dmitry-weirdo** [comment]
Setting

```java
            client.setHttpClient(new OkHttp4Client());
```

according to the documentation helped.
