### ISSUE TITLE
NullPointerException in model.databases.Database.hashCode

### ISSUE THREAD

**Issue by heuermh** [seratch/notion-sdk-jvm#51]
Are Kotlin model data classes appropriate for use as keys in e.g. `Map`s?  I am running into NullPointerException with

```java
Database database = client.retrieveDatabase(databaseId);
MutableNetwork<Database, DatabaseProperty> network = NetworkBuilder.directed().build();
network.addNode(database);
```

```
java.lang.NullPointerException
	at notion.api.v1.model.databases.Database.hashCode(Database.kt)
	at java.base/java.util.HashMap.hash(HashMap.java:340)
	at java.base/java.util.HashMap.containsKey(HashMap.java:592)
	at com.google.common.graph.MapIteratorCache.containsKey(MapIteratorCache.java:104)
	at com.google.common.graph.StandardNetwork.containsNode(StandardNetwork.java:198)
	at com.google.common.graph.StandardMutableNetwork.addNode(StandardMutableNetwork.java:57)
```

**Comment by seratch** [comment]
Hi @heuermh, thanks for sharing this. It seems that the Kotlin runtime behaves this way and I am still unsure about the best way to resolves this or a reasonable workaround for it. 

At this moment, I don't recommend using the object as the key that can be used for comparison using the hashCode method result. Instead, you can use the Notion database ID string for the keys.

**Comment by heuermh** [comment]
@seratch Please feel free to close this issue.
